version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "allocation"
      POSTGRES_USER: "allocation"
      POSTGRES_PASSWORD: "abc123"